spring:
  config:
    import: secret.yml
  datasource:
    driver-class-name: org.postgresql.Driver
  application:
    name: jobs
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true

  logging:
    level:
      org:
        springframework:
          security: DEBUG
          springframework: DEBUG
